{{- if and .Values.jaeger.enabled .Values.jaeger.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    app: jaeger
    {{- include "observability.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.jaeger.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.jaeger.ingress.ingressClassName }}
  {{- if .Values.jaeger.ingress.tls }}
  tls:
  {{- range .Values.jaeger.ingress.tls }}
  - hosts:
    {{- range .hosts }}
    - {{ . }}
    {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
  {{- range .Values.jaeger.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jaeger-query
            port:
              number: {{ $.Values.jaeger.service.ports.query }}
  {{- end }}
{{- end }}
