apiVersion: v1
kind: Secret
metadata:
  name: health-api-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app: health-api
    app.kubernetes.io/name: health-api
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  secret-key: {{ .Values.secrets.secretKey | quote }}
  database-password: {{ .Values.secrets.database.password | quote }}
  redis-password: {{ .Values.secrets.redis.password | quote }}
  minio-access-key: {{ .Values.secrets.minio.accessKey | quote }}
  minio-secret-key: {{ .Values.secrets.minio.secretKey | quote }}
  rabbitmq-password: {{ .Values.secrets.rabbitmq.password | quote }}
