apiVersion: v1
kind: Secret
metadata:
  name: etl-engine-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app: etl-engine
    app.kubernetes.io/name: etl-engine
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  database-password: {{ .Values.secrets.database.password | quote }}
  minio-access-key: {{ .Values.secrets.minio.accessKey | quote }}
  minio-secret-key: {{ .Values.secrets.minio.secretKey | quote }}
  rabbitmq-user: {{ .Values.secrets.rabbitmq.user | quote }}
  rabbitmq-password: {{ .Values.secrets.rabbitmq.password | quote }}
